import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv("retail_sales.csv")
print("Retail Sales Dataset")
print(df)
print("\nDataset Information")
print(df.info())
print("\nStatistics")
print(df.describe())
print("\nTotal Sales:", df["Sales"].sum())
print("\nSales by Store")
print(df.groupby("Store")["Sales"].sum())
print("\nSales by Category")
print(df.groupby("Category")["Sales"].sum())
df.groupby("Store")["Sales"].sum().plot(kind="bar")
plt.title("Store Performance")
plt.xlabel("Store")
plt.ylabel("Sales")
plt.show()